# Generated by Django 4.2.3 on 2023-07-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
