# Generated by Django 4.2.3 on 2023-07-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_medicalrecord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
