# Generated by Django 4.2.3 on 2023-07-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_medicalrecord_age_medicalrecord_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
