# Generated by Django 4.2.3 on 2023-07-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_alter_medicalrecord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='home_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='work_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
